SELECT 
    C.CAR_ID, 
    C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE 
AND P.DURATION_TYPE = '30일 이상'


WHERE C.CAR_TYPE IN ('SUV','세단') 

AND NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
    AND H.START_DATE <= '2022-11-30'
    AND H.END_DATE >= '2022-11-01'
)

AND FLOOR(C.DAILY_FEE *30*(100-P.DISCOUNT_RATE)/100)
    BETWEEN 500000 AND 1999999

ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;


