

SELECT ID,
    CASE 
        WHEN 100 * (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) <= 25 THEN 'CRITICAL'
        WHEN 100 * (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) <= 50 THEN 'HIGH'
        WHEN 100 * (PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)) <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;