-- 각 세대별 대장균 ID를 찾자.


WITH RECURSIVE GEN AS(
    -- 초기값 세팅(1세대 대장균)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, GENERATION+1 AS GENERATION
    FROM GEN G
        JOIN ECOLI_DATA E
        ON G.ID=E.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA 
    WHERE ECOLI_DATA.PARENT_ID=GEN.ID
)
GROUP BY GENERATION
ORDER BY GENERATION