-- 코드를 입력하세요


-- ID, TOTAL_SALES 테이블 만들기
-- USED_GOODS_USER랑 JOIN 

WITH TMP AS(
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)


SELECT B.USER_ID, B.NICKNAME, A.TOTAL_SALES
FROM TMP A
    JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
ORDER BY TOTAL_SALES